name: gocosmos

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test driver
    runs-on: windows-latest
    steps:
      - name: Set up Go env
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          choco install azure-cosmosdb-emulator
          & "C:\Program Files\Azure Cosmos DB Emulator\Microsoft.Azure.Cosmos.Emulator.exe" /DisableRateLimiting /NoUI /NoExplorer
          Start-Sleep -s 60
          try { Invoke-RestMethod -Method GET https://127.0.0.1:8081/ } catch {}
          netstat -nt
          $env:COSMOSDB_DRIVER='gocosmos'
          $env:COSMOSDB_URL='AccountEndpoint=https://127.0.0.1:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='
          go test -cover -coverprofile="coverage_driver.txt" -v -count 1 -p 1 -run "Test_" .
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: driver
          name: driver

  test:
    name: Test RestClient non-query
    runs-on: windows-latest
    steps:
      - name: Set up Go env
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          choco install azure-cosmosdb-emulator
          & "C:\Program Files\Azure Cosmos DB Emulator\Microsoft.Azure.Cosmos.Emulator.exe" /DisableRateLimiting /NoUI /NoExplorer
          Start-Sleep -s 120
          try { Invoke-RestMethod -Method GET https://127.0.0.1:8081/ } catch {}
          netstat -nt
          $env:COSMOSDB_DRIVER='gocosmos'
          $env:COSMOSDB_URL='AccountEndpoint=https://127.0.0.1:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='
          go test -cover -coverprofile="coverage_restclient_nonquery.txt" -v -count 1 -p 1 -run "TestRestClient_[^Q]" .
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: restclient_nonquery
          name: restclient_nonquery

  test:
    name: Test RestClient query
    runs-on: windows-latest
    steps:
      - name: Set up Go env
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          choco install azure-cosmosdb-emulator
          & "C:\Program Files\Azure Cosmos DB Emulator\Microsoft.Azure.Cosmos.Emulator.exe" /DisableRateLimiting /NoUI /NoExplorer
          Start-Sleep -s 120
          try { Invoke-RestMethod -Method GET https://127.0.0.1:8081/ } catch {}
          netstat -nt
          $env:COSMOSDB_DRIVER='gocosmos'
          $env:COSMOSDB_URL='AccountEndpoint=https://127.0.0.1:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='
          go test -cover -coverprofile="coverage_restclient_query.txt" -v -count 1 -p 1 -run "TestRestClient_QueryDocuments" .
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: restclient_query
          name: restclient_query

  test:
    name: Test other
    runs-on: windows-latest
    steps:
      - name: Set up Go env
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          choco install azure-cosmosdb-emulator
          & "C:\Program Files\Azure Cosmos DB Emulator\Microsoft.Azure.Cosmos.Emulator.exe" /DisableRateLimiting /NoUI /NoExplorer
          Start-Sleep -s 120
          try { Invoke-RestMethod -Method GET https://127.0.0.1:8081/ } catch {}
          netstat -nt
          $env:COSMOSDB_DRIVER='gocosmos'
          $env:COSMOSDB_URL='AccountEndpoint=https://127.0.0.1:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='
          go test -cover -coverprofile="coverage_other.txt" -v -count 1 -p 1 -run "TestNew" .
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: other
          name: other
